name: Bug report
description: File a bug/issue report
labels: ['bug :bug:']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A clear and concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to ...
      2. Tap on ...
      3. Scroll down to ...
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Device Configuration
    description: |
      Describe your device configuration as precise as possible. For exemple:
        - **AdAway version**: 5.1.2
        - **Ad-blocker mode**: root or vpn
        - **Device**: Pixel 6a
        - **Android version**: 12
        - **Root version**: Magisk 24.1
    value: |
        - AdAway version: 
        - Ad-blocker mode: 
        - Device: 
        - Android version: 
        - Root version: 
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context and screenshots
    description: |
      Add any other context like logcat and screenshots about the problem here.
      Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs.
      Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
